permalink: /:title

markdown: rdiscount

auto: true
pygments: true

name: Rascal - Meta Programming Language
title: Rascal - Meta Programming Language

production_url: http://cwi-swat.github.io/rascal/
